# Numpy

In [2]:
a1= list()
a1.append(1)
a1.append(111)
a1

[1, 111]

In [3]:
a1[0]

1

In [4]:
a1[1]

111

In [8]:
a1[-1]

111

In [9]:
a1.append('treinta')

## Importando a numpy

In [16]:
import numpy as np

In [17]:
np.array([])

array([], dtype=float64)

## Creando Arreglos

## Arreglo dimensión 0

In [20]:
num= np.array(44)

## Arreglo dimensión 1

In [18]:
arreglo1=np.array([0,1,2,3,4,5,6,7,8,9])
arreglo2=np.array([20,40,60,80,100])

In [19]:
type(arreglo1)

numpy.ndarray

## Arreglo dimensión 2

In [22]:
arreglo2D= np.array([[1,2,3],[4,5,6],[7,8,9]])
arreglo2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arreglo dimensión 3

In [23]:
arreglo3D= np.array([[[1,0],[2,0],[3,0]],[[4,0],[5,0],[6,0]],[[7,0],[8,0],[9,0]]])
arreglo3D

array([[[1, 0],
        [2, 0],
        [3, 0]],

       [[4, 0],
        [5, 0],
        [6, 0]],

       [[7, 0],
        [8, 0],
        [9, 0]]])

In [24]:
arreglo3D.ndim

3

In [26]:
arreglo2D.ndim

2

In [27]:
arreglo1.ndim

1

In [28]:
num.ndim

0

## Acceder a los elementos de un arreglo

In [29]:
arreglo1[0]

0

In [30]:
arreglo1[1]

1

In [32]:
arreglo2D[0]

array([1, 2, 3])

In [33]:
arreglo2D[0,0]

1

In [34]:
arreglo3D[2]

array([[7, 0],
       [8, 0],
       [9, 0]])

In [35]:
arreglo3D[2][1]

array([8, 0])

In [36]:
arreglo3D[2][1][0]

8

In [42]:
arreglo3D[:2]

array([[[1, 0],
        [2, 0],
        [3, 0]],

       [[4, 0],
        [5, 0],
        [6, 0]]])

In [43]:
arreglo3D[:-1]

array([[[1, 0],
        [2, 0],
        [3, 0]],

       [[4, 0],
        [5, 0],
        [6, 0]]])

In [44]:
arreglo3D[1:2]

array([[[4, 0],
        [5, 0],
        [6, 0]]])

In [55]:
arreglo3D[1:3][1][2][0]

9

In [60]:
arreglo2D[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arreglo1[1:8:3]

array([1, 4, 7])

### Tipos de datos - dtype

In [64]:
arreglo1.dtype

dtype('int32')

In [67]:
arreglo2D.dtype

dtype('int32')

In [ ]:
arreglo1.dtype

In [68]:
arregloDias = np.array([1, 2, 3, 4, 5, 6, 7], dtype='S')

In [69]:
arregloDias.dtype

dtype('S1')

In [70]:
print(arregloDias)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']


In [72]:
numeros=np.array([3,5,7,9],dtype='i2')

In [73]:
print(numeros)

[3 5 7 9]


In [74]:
arreglo1.shape

(10,)

In [75]:
arreglo2D.shape

(3, 3)

In [76]:
arreglo3D.shape

(3, 3, 2)

In [79]:
len(arreglo3D)

3

In [83]:
arreglo2D.size

9

In [84]:
arreglo3D.size

18

In [85]:
arr3DCopy=arreglo3D.copy()

In [86]:
arr1DCopy=arreglo1.copy()

In [88]:
arr1DCopy.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
arr1DCopy.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [93]:
arreglo3D_lineal=arr3DCopy.reshape(18)

In [94]:
arreglo3D_lineal.ndim

1

In [95]:
arreglo3D_lineal

array([1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0])

In [96]:
arr3DCopy

array([[[1, 0],
        [2, 0],
        [3, 0]],

       [[4, 0],
        [5, 0],
        [6, 0]],

       [[7, 0],
        [8, 0],
        [9, 0]]])

# Matrices

In [101]:
A=np.matrix('1 2 0; 3 4 1')

In [102]:
A

matrix([[1, 2, 0],
        [3, 4, 1]])

In [103]:
A.size

6

In [104]:
A.ndim

2

In [105]:
A.shape

(2, 3)

In [106]:
A.dtype

dtype('int32')

In [109]:
At=A.T

In [110]:
At

matrix([[1, 3],
        [2, 4],
        [0, 1]])

In [111]:
At.shape

(3, 2)

In [113]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [114]:
matrix_unos=np.matrix(np.ones((4,2)))

In [115]:
matrix_unos

matrix([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [116]:
matrix_unos.dtype

dtype('float64')

In [117]:
#Matriz inversa de A
A.I

matrix([[-0.77777778,  0.44444444],
        [ 0.88888889, -0.22222222],
        [-1.22222222,  0.55555556]])

In [118]:
#Matriz Conjugada Transpuesta de A
A.H

matrix([[1, 3],
        [2, 4],
        [0, 1]])

## Resolver matrices 

In [136]:
B = np.matrix(' 3, 5; 7, 9')
B

matrix([[3, 5],
        [7, 9]])

In [121]:
#Vector inter
b= np.array([2,4])

In [139]:
#Vector solución
x= np.linalg.solve(B,b)
x

array([0.25, 0.25])

In [141]:
y = np.array([-1,-2])

In [143]:
x1= np.linalg.solve(B,y)
x1

array([-0.125, -0.125])

In [145]:
A.diagonal()

matrix([[1, 4]])

In [146]:
B.diagonal()

matrix([[3, 9]])